FROM registry.fedoraproject.org/fedora-toolbox:44
# basic ui layer
RUN dnf install -y libXcomposite libXdamage libXfixes libXrandr libXtst alsa-lib atk at-spi2-atk at-spi2-core dbus-libs libxkbcommon expat libX11 libXext fontconfig gtk3 cairo pango nspr nss libglvnd-glx mesa-libGL mesa-libEGL libglvnd-opengl \
    --exclude=openh264 \
    && dnf clean all
RUN wget https://github.com/Happ-proxy/happ-desktop/releases/latest/download/Happ.linux.x64.rpm && dnf install -y Happ.linux.x64.rpm
