if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
PATH="$HOME/.opencode/bin:$PATH"
export PATH
shopt -s histappend
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoreboth
export HISTIGNORE="ls:pwd:exit:clear:git status:git branch:edit-fzf"
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
export REGISTRY_AUTH_FILE=/var/home/nvs/.config/containers/auth.json
export EDITOR="micro"

command -v fzf >/dev/null 2>&1 && eval "$(fzf --bash)"

if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

alias edit="flatpak run org.gnome.TextEditor"
alias edit-fzf='edit $(fzf)'
alias nano-fzf='nano $(fzf)'
alias micro-fzf='micro $(fzf)'
alias chrome-testing='toolbox run -c dev-utils chrome'
alias docx2pdf='toolbox run -c sys-utils -- env SAL_USE_VCLPLUGIN=svp soffice --headless --convert-to pdf --outdir "$(dirname -- "$1")" "$1"'

git-clean() {
  git checkout master; git branch | grep -v master | grep -v release | grep -v develop | grep -v main | xargs git branch -D
}

git-commit() {
  task=$(git branch --show-current | grep -Eo "DEV-[0-9]+") && git commit -m "$task $1"
}

git-add-and-commit() {
  task=$(git branch --show-current | grep -Eo "DEV-[0-9]+") && git add . && git commit -m "$task $1"
}

proxy-activate() {
  export HTTP_PROXY=http://127.0.0.1:10809
  export HTTPS_PROXY=http://127.0.0.1:10809
  export NO_PROXY=localhost,127.0.0.1
}

dc-start() {
    podman start $(podman ps -a --filter "label=$1" --filter "status=exited" -q) 2>/dev/null
}

dc-stop() {
    podman stop $(podman ps -a --filter "label=$1" --filter "status=running" -q) 2>/dev/null
}

dc-stop-all() {
    podman stop $(podman ps -a --filter "label=devcontainer.local_folder" --filter "status=running" -q) 2>/dev/null
}

dc-clean-all() {
    podman rm -f $(podman ps -a --filter "label=devcontainer.local_folder" --filter "status=exited" -q) 2>/dev/null
}

dc-clean() {
    podman rm -f $(podman ps -a --filter "label=$1" --filter "status=exited" -q) 2>/dev/null
}

tc-clean() {
    podman rm -f $(podman ps -a --filter "label=org.testcontainers" -q) 2>/dev/null
}

openrouter-limits() {
    apikey=$(cat ~/.config/openrouter.key)
    HTTPS_PROXY=http://127.0.0.1:10809 curl -H "Authorization: Bearer $apikey" https://openrouter.ai/api/v1/auth/key 2>/dev/null | jq
}

opencode() {
    command opencode "$@"
    printf '\e[?1000l\e[?1002l\e[?1003l\e[?1006l'       # disable mouse tracking
    while read -rs -t 0.2 -N 512 oc_trash; do :; done # clear input buffer
    printf '\r\e[K' # erase leftover mouse-tracking output
}
